apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "2Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/exports/mariadb"
